use std::collections::HashMap;

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Grid primitives
// ---------------------------------------------------------------------------

/// RGBA pixel: (red, green, blue, alpha).
pub type Pixel = (u8, u8, u8, u8);

/// 2D sprite: rows of pixels. `sprite[y][x]` = pixel at (x, y).
pub type SpriteData = Vec<Vec<Pixel>>;

/// Tile coordinate on the farm grid: (col, row).
pub type TilePos = (u16, u16);

// ---------------------------------------------------------------------------
// Tile types
// ---------------------------------------------------------------------------

/// Tile type stored in the farm grid. `repr(u8)` matches the serialized format.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum TileType {
    Void = 0,
    Grass = 1,
    GrassDark = 2,
    Dirt = 3,
    DirtDark = 4,
    Water = 5,
    Sand = 6,
    Stone = 7,
    Fence = 100,
}

impl TileType {
    /// Convert a raw byte to a tile type.
    pub fn from_u8(value: u8) -> Self {
        match value {
            0 => Self::Void,
            1 => Self::Grass,
            2 => Self::GrassDark,
            3 => Self::Dirt,
            4 => Self::DirtDark,
            5 => Self::Water,
            6 => Self::Sand,
            7 => Self::Stone,
            100 => Self::Fence,
            _ => Self::Void,
        }
    }

    /// Returns true if this tile is walkable ground.
    pub fn is_floor(self) -> bool {
        matches!(
            self,
            Self::Grass | Self::GrassDark | Self::Dirt | Self::DirtDark | Self::Sand | Self::Stone
        )
    }
}

// ---------------------------------------------------------------------------
// Direction and state enums
// ---------------------------------------------------------------------------

/// Cardinal direction for character facing and movement.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Direction {
    Down,
    Up,
    Left,
    Right,
}

/// Character finite state machine state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CharState {
    Idle,
    Walk,
    Type,
}

/// Animation type for sprite lookup.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum AnimType {
    Walk,
    Type,
    Read,
    Fish,
    Farm,
    Harvest,
}

/// Agent status inferred from JSONL parsing and heuristic timers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum AgentStatus {
    Active,
    Idle,
    Waiting,
    Permission,
    /// Session file went stale — agent is inside a building, hidden from view.
    Dormant,
}

/// Type of produce generated by agent work.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ProduceType {
    Wheat,
    Fruit,
    Fish,
}

/// Speech bubble kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BubbleKind {
    Permission,
    Waiting,
}

/// Companion animal kind for sub-agent visualization.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CompanionKind {
    Chicken,
    Cat,
    Dog,
}

// ---------------------------------------------------------------------------
// Agent events (produced by JSONL parser, consumed by App)
// ---------------------------------------------------------------------------

/// Events extracted from JSONL records by the watcher parser.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum AgentEvent {
    ToolStart {
        tool_id: String,
        tool_name: String,
    },
    ToolDone {
        tool_id: String,
    },
    TurnEnd,
    TextOnly,
    SubAgentToolStart {
        parent_tool_id: String,
        tool_id: String,
        tool_name: String,
    },
    SubAgentToolDone {
        parent_tool_id: String,
        tool_id: String,
    },
    SubAgentSpawn {
        parent_tool_id: String,
    },
    BashProgress {
        tool_id: String,
    },
    BackgroundAgentDetected {
        tool_id: String,
    },
}

// ---------------------------------------------------------------------------
// Layout serialization types
// ---------------------------------------------------------------------------

/// HSL-based tile color for colorization.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TileColor {
    pub h: f32,
    pub s: f32,
    pub b: f32,
}

/// Furniture placement in the serialized layout.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlacedFurniture {
    pub uid: String,
    #[serde(rename = "type")]
    pub furniture_type: String,
    pub col: i16,
    pub row: i16,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<TileColor>,
}

impl PlacedFurniture {
    /// Shorthand constructor with no color override.
    pub fn new(uid: &str, furniture_type: &str, col: i16, row: i16) -> Self {
        Self {
            uid: uid.to_owned(),
            furniture_type: furniture_type.to_owned(),
            col,
            row,
            color: None,
        }
    }
}

/// Serializable office layout. Compatible with the VS Code extension format.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OfficeLayout {
    pub version: u32,
    pub cols: u16,
    pub rows: u16,
    pub tiles: Vec<u8>,
    pub furniture: Vec<PlacedFurniture>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tile_colors: Option<HashMap<String, TileColor>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layout_revision: Option<u32>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tile_type_from_u8_known_values() {
        assert_eq!(TileType::from_u8(0), TileType::Void);
        assert_eq!(TileType::from_u8(1), TileType::Grass);
        assert_eq!(TileType::from_u8(2), TileType::GrassDark);
        assert_eq!(TileType::from_u8(3), TileType::Dirt);
        assert_eq!(TileType::from_u8(4), TileType::DirtDark);
        assert_eq!(TileType::from_u8(5), TileType::Water);
        assert_eq!(TileType::from_u8(6), TileType::Sand);
        assert_eq!(TileType::from_u8(7), TileType::Stone);
        assert_eq!(TileType::from_u8(100), TileType::Fence);
    }

    #[test]
    fn tile_type_from_u8_unknown_maps_to_void() {
        assert_eq!(TileType::from_u8(8), TileType::Void);
        assert_eq!(TileType::from_u8(50), TileType::Void);
        assert_eq!(TileType::from_u8(255), TileType::Void);
    }

    #[test]
    fn tile_type_is_floor() {
        assert!(TileType::Grass.is_floor());
        assert!(TileType::GrassDark.is_floor());
        assert!(TileType::Dirt.is_floor());
        assert!(TileType::DirtDark.is_floor());
        assert!(TileType::Sand.is_floor());
        assert!(TileType::Stone.is_floor());
        assert!(!TileType::Void.is_floor());
        assert!(!TileType::Water.is_floor());
        assert!(!TileType::Fence.is_floor());
    }

    #[test]
    fn tile_type_unknown_maps_to_void() {
        assert_eq!(TileType::from_u8(8), TileType::Void);
    }
}
